import React, { useState, useEffect } from "react";
import Header from "./Header";
import Head from "next/head";
import { bgStyle } from "styles/backgroundStyle";
import { useTheme } from "next-themes";
const Layout = ({ children, className, dashboard }) => {
  const { systemTheme, theme } = useTheme();
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    console.clear();
    console.log("Hi SURE! Hope you enjoy 😀 - MATT");
    setMounted(true);
  }, []);

  if (!mounted) return null;

  const currentTheme = theme === "system" ? systemTheme : theme;

  return (
    <>
      <Head>
        <title>Rocket Insurance | SURE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          backgroundColor: currentTheme === "dark" ? "black" : "white",
          ...bgStyle,
        }}
        className={`${className} min-h-full`}
      >
        <Header dashboard={dashboard} />
        <main className="flex-1 ">{children}</main>
      </div>
    </>
  );
};

export default Layout;
